### ISSUE TITLE
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 189: ordinal not in range(128)

### ISSUE THREAD

**Issue by ljhanson** [click-contrib/click-spinner#17]
Trying to install blindspin on FreeBSD 10.  Install clean on python 2.7, python 3.6 fails with the following error:
```
Collecting blindspin
  Downloading blindspin-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ys3jzeiy/blindspin/setup.py", line 7, in <module>
        readme = f.read()
      File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 189: ordinal not in range(128)
```

**Comment by yoavram** [comment]
Why are you trying to install blindspin and what does it have to do with click-spinner?

**Comment by ljhanson** [comment]
Aplologies.  Wrong tab.
